### PR TITLE
Support YUV 4:4:4 streaming

### PR DESCRIPTION
**Pull request by ns6089**
moonlight_yuv444
---
yuv444_option
---
Add support for YUV 4:4:4 streaming

moonlight-common-c pull request: https://github.com/moonlight-stream/moonlight-common-c/pull/91 merged
sunshine pull request: https://github.com/LizardByte/Sunshine/pull/2533 draft

Todo, in no particular order:
- [ ] Add Vulkan headers to CI environment
  - Probably the easiest way is to add them to moonlight-qt-prebuilts submodule, collected from https://github.com/KhronosGroup/Vulkan-Headers
- [ ] Test decoding on intel (i)gpus
- [x] Implement "YUV 4:4:4" option on settings page
  - implemented as dumb switch, no intelligent graying out
- [x] Generate and include missing blobs of encoded video data used in decoder availability auto-detection
  - may want to revise the methodology
- [x] Change plvk renderer heuristics to support 10-bit SDR video decoding on SDR displays, currently it tests for `VK_COLOR_SPACE_HDR10_ST2084_EXT` and it fails when display is not in HDR mode
  - Removed this check altogether, libplacebo might need some reconfiguration to handle tone mapping gracefully
- [x] Investigate and possibly resolve color conversion errors
  - Full Range had issues on sunshine's side, fixed in the same 4:4:4 PR
  - Rec.601 should never be requested on third-party renderers because it has different primaries from sRGB

### CODE REVIEW

**Comment by ns6089** [comment]
@cgutman I probably can't do more on moonlight side (moonlight-common-c included) without feedback. Format selection logic appears overcomplicated to me, so I've probably missed some corner cases, and you might prefer to do some things differently altogether. Also if you prefer, you can simply take this over after 5.1 is released, this may prevent the needless back-and-forth.

**Comment by moi952** [comment]
Hi @ns6089, this development is planned to be developed on moonlight-android?

**Comment by ns6089** [comment]
> this development is planned to be developed on moonlight-android?
Not anytime soon, no hardware support.

**Comment by ns6089** [comment]
- rebased against latest master
- added 2x multiplier to default bitrate when 4:4:4 option is enabled

**Comment by Decbuan** [comment]
> * 根据最新的 master 进行重新定位
> * 启用 4:4:4 选项时，默认比特率增加 2 倍乘数

Keep it up! Looking forward to the success of YUV444!! For high-end computer users and those with WiFi 6 or above, we hope for higher bitrate requests and better picture encoding and transmission.

**Comment by Decbuan** [comment]
> * 根据最新的 master 进行重新定位
> * 启用 4:4:4 选项时，默认比特率增加 2 倍乘数

I have obtained the version you uploaded on AppVeyor, and I know that this requires support for synchronous encoding by Sunshine, which is not currently in effect. What I want to point out is that when I enable the 444 button, my bitrate can only go up to 114mbps. If 444 is implemented, it shouldn't be limited to this range, right?

**Comment by ns6089** [comment]
- disabled H.264 4:4:4 for now due to lack of hardware decoders and incomplete (at least to my understanding) software decoding support on plvk backend

**Comment by moi952** [comment]
@ns6089 Thank you for your work !
I see that the application is not building for Windows, is this normal?

**Comment by ns6089** [comment]
> I see that the application is not building for Windows, is this normal?

The repository with binary dependencies needs to be updates, I'm trying to get this sorted out.

**Comment by ns6089** [comment]
Can't be done before 6.0.1 hotfix goes live it seems.

**Comment by moi952** [comment]
Even recovering v6 it doesn't build?

**Comment by ns6089** [comment]
> Even recovering v6 it doesn't build?

If you're trying to build outside of CI on your own computer, this PR currently contains commits that revert binary deps to somewhat functional state. But you also need local vulkan headers, with %VULKAN_SDK% env variable pointing at them. installing SDK from https://vulkan.lunarg.com/sdk/home#windows should be enough.

**Comment by cgutman** [comment]
@ns6089 I've updated the binary deps, so this should be ready to land once you rebase and resolve the conflicts.

**Comment by ns6089** [comment]
@cgutman Great, I will get onto it.
In the meantime, what are we going to do with vulkan headers on Windows in general, and in CI in particular?
We can grab a copy from https://github.com/KhronosGroup/Vulkan-Headers and put it into build-deps as well. Or just add it as a submodule, but not sure if anything other than Windows can make use of this.

**Comment by ns6089** [comment]
Rebased. Everything appears to be working including software decoding.
Now we just need to decide what to do with vulkan headers.

**Comment by cgutman** [comment]
Okay, everything should be ready now. You can rebase one final time and drop your changes to `app/app.pro` then we can get this merged.

**Comment by ns6089** [comment]
@cgutman Done. Sunshine side is ready for review too.

**Comment by Kobain-Seo** [comment]
I faced green screen. I commented at PR of sunshine and attached moonlight logs.

[Uploading Moonlight-1721211751.log…]()

**Comment by KWottrich** [comment]
> I faced green screen. I commented at PR of sunshine and attached moonlight logs.

You mentioned building Sunshine and Moonlight yourself... just to rule out a misconfigured build environment, you should get the builds from here. The AppVeyor builds for this side (Moonlight) are available to download now that the Vulkan headers have been hooked up. You can see them at https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/50226576. Click the build matching your Moonlight client's OS and then click the Artifacts tab. If you happen to have a Windows client, here is the direct link to the portable EXE: https://ci.appveyor.com/api/buildjobs/1pj6d2ug6w0281d2/artifacts/MoonlightPortable-x64-r2535.zip

**Comment by KWottrich** [comment]
I have downloaded the Sunshine CI build for Windows from the Sunshine PR (https://github.com/LizardByte/Sunshine/actions/runs/9969085431/artifacts/1710861456) and the Moonlight CI build for Windows from AppVeyor (https://ci.appveyor.com/api/buildjobs/1pj6d2ug6w0281d2/artifacts/MoonlightPortable-x64-r2535.zip).  My Sunshine host has a RTX 3070 with the latest drivers, and my client has a laptop RTX 3050 Ti.  When attempting to connect with YUV 4:4:4 enabled in Moonlight, the application crashes.  Here's my log file, and can add the dmp if needed:
[Moonlight-1721224357.log](https://github.com/user-attachments/files/16266864/Moonlight-1721224357.log)

Using those same CI builds for both Sunshine and Moonlight, I can stream normally with YUV 4:4:4 disabled.

**Comment by ns6089** [comment]
```
00:01:10 - SDL Warn (0): Vulkan device 'AMD Radeon(TM) Graphics' does not support VK_KHR_video_decode_h265
00:01:10 - SDL Info (0): Vulkan rendering device chosen: NVIDIA GeForce RTX 3050 Ti Laptop GPU
```
(The usual at this point) NVIDIA Optimus problems I guess. Maybe it will work it you change gpu priority.

**Comment by KWottrich** [comment]
> (The usual at this point) NVIDIA Optimus problems I guess. Maybe it will work it you change gpu priority.

Good point, @ns6089. I rebooted my laptop in dGPU-only mode and re-ran the test. Still crashes with YUV 4:4:4:
[Moonlight-1721226041.log](https://github.com/user-attachments/files/16267597/Moonlight-1721226041.log)

**Comment by ns6089** [comment]
Then I must ask for the dump (even though the problem is probably not in scope of this pull request). Just make sure the particular moonlight instance doesn't have any credentials you'd rather keep private.

**Comment by vadash** [comment]
4:4:4 works fine. Good job guys
image
3070 host @ 537.58, 2060 client @ 537.58

**Comment by michaelgilly** [comment]
Would you be willing to share a compiled build for others to test? I’m very interested. Thank you for the work.

**Comment by michaelgilly** [comment]
I had the same issue as @KWottrich, but I'm not using a laptop, just an RTX 3050 with the Intel iGPU disabled.

[Moonlight-1721236488.log](https://github.com/user-attachments/files/16272202/Moonlight-1721236488.log)

**Comment by KWottrich** [comment]
> @ns6089 Here's the dump tied to the crash AFTER I disabled optimus and was only using the 3050 Ti: [Moonlight-1721226070.dmp](https://github.com/user-attachments/files/16268121/Moonlight-1721226070.dmp)

Looks like the crash is in avcodec_61, which means the crash is in FFmpeg

```
CONTEXT:  (.ecxr)
rax=0000000000000001 rbx=000002958cb63900 rcx=000002958cb63900
rdx=0000029580bd9440 rsi=00000295fa9ea240 rdi=0000029589b3c4e0
rip=00007ffd4e47a429 rsp=000000c215faddf0 rbp=000000c215fadfb0
 r8=0000000000000000  r9=0000000004000000 r10=0000000000000000
r11=0000000000000001 r12=00000295968d9b40 r13=0000029580d44f40
r14=0000029580bd9440 r15=000000c215faeec0
iopl=0         nv up ei pl nz na po nc
cs=0033  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010206
avcodec_61+0x32a429:
00007ffd`4e47a429 498b8060010000  mov     rax,qword ptr [r8+160h] ds:00000000`00000160=????????????????
Resetting default scope

EXCEPTION_RECORD:  (.exr -1)
ExceptionAddress: 00007ffd4e47a429 (avcodec_61+0x000000000032a429)
   ExceptionCode: c0000005 (Access violation)
  ExceptionFlags: 00000000
NumberParameters: 2
   Parameter[0]: 0000000000000000
   Parameter[1]: 0000000000000160
Attempt to read from address 0000000000000160

PROCESS_NAME:  Moonlight.exe

READ_ADDRESS:  0000000000000160 

ERROR_CODE: (NTSTATUS) 0xc0000005 - The instruction at 0x%p referenced memory at 0x%p. The memory could not be %s.
```

**Comment by Kobain-Seo** [comment]
> I faced green screen. I commented at PR of sunshine and attached moonlight logs.
> 
> Uploading Moonlight-1721211751.log…

Software decoding works. So I think it is about intel igpu decoding.

**Comment by ns6089** [comment]
I think intel drivers on windows are lagging behind in terms of `VK_KHR_video_decode` support (which is understandable because the whole thing is very new). On linux the situation looks much better.

@cgutman Not sure if we should add intel 4:4:4 decoding to d3d11va path through their vendor caps. It will complicate the code and will require some new (admittedly rather simple) shaders with slightly different color conversion (currently sunshine/moonlight use non-standard UV center which I had to change back to standard for 4:4:4 encoding on sunshine side for compatibility with libplacebo).

**Comment by ns6089** [comment]
> Intel? Nobody mentioned using that.

[I have the same green screen issue than @Kobain-Seo above, with a RTX A2000 as a host and an Intel Xe (13th Gen) as a client.](https://github.com/LizardByte/Sunshine/issues/2533#issuecomment-2235829218)

> on linux where they aren't shipping the video extensions

True I suppose, the merge request to hasvk got stalled (I misread current support status in the corresponding mpv discussion)

**Comment by KWottrich** [comment]
I have some additional notes on my experiences:

- I have reproduced the crash after installing Sunshine (from https://github.com/LizardByte/Sunshine/pull/2533) on my laptop, and building/running this branch of Moonlight on my desktop with a RTX 3070 on the latest NVidia drivers (560.70). My desktop has a 5800x3D, so there's no risk of complication with iGPU/Optimus weirdness. The crash happens at exactly the same place, which is the first time `submitDecodeUnit` is called after connecting to the host.
- I do not get the crash if I disable YUV 4:4:4
- I do not get the crash if I **enable** YUV 4:4:4, but force software decoding

I'm very experienced with Java debugging but new to debugging C, so if there's any additional info I can provide from my system(s), please let me know! I can set breakpoints and/or share values at any given line of code immediately prior to the call triggering the exception

**Comment by ns6089** [comment]
@KWottrich Here's a small (less than 3MB) 4:4:4 HEVC 8-bit sample 
https://github.com/user-attachments/assets/164e93f8-4c8a-4686-88ed-e2af2f963d17

Try opening it in in mpv https://mpv.io/
while forcing vulkan decoding with the following args
`mpv --vo=gpu-next --gpu-api=vulkan --hwdec=vulkan --gpu-context=winvk that_file.mp4`

If it plays and the console says something like this:
```
Using hardware decoding (vulkan).
VO: [gpu-next] 1920x1080 vulkan[nv24]
```
Then we can probably do something on our end. Otherwise it's a driver bug that has to be fixed by nvidia (they've been fixing them continuously since vulkan video extensions got introduced).

**Comment by ns6089** [comment]
>>   on linux where they aren't shipping the video extensions

> True I suppose, the merge request to hasvk got stalled (I misread current support status in the corresponding mpv discussion)

Actually, no (something something gaslighting is not real). ANV driver seems to have support, while HASVK is stuck in a limbo. No idea about 4:4:4 though.

@Kobain-Seo
> It showed green screen.

Yeah, windows driver at this moment seem to have this problem. Intel is actively working on this driver though.

**Comment by KWottrich** [comment]
> Try opening it in in mpv https://mpv.io/ while forcing vulkan decoding with the following args `mpv --vo=gpu-next --gpu-api=vulkan --hwdec=vulkan --gpu-context=winvk that_file.mp4`

Yep, file fails to play. Log output from `mpv --vo=gpu-next --gpu-api=vulkan --hwdec=vulkan --gpu-context=winvk --msg-level=vd=v that_file.mp4`:
```
● Video  --vid=1  (hevc 1920x1080 30 fps) [default]
File tags:
 Artist: Blender Foundation 2008, Janus Bager Kristensen 2013
 Comment: Creative Commons Attribution 3.0 - http://bbb3d.renderfarming.net
 Composer: Sacha Goedegebure
 Genre: Animation
 Title: Big Buck Bunny, Sunflower version
[vd] Container reported FPS: 30.000000
[vd] Codec list:
[vd]     hevc - HEVC (High Efficiency Video Coding)
[vd]     hevc_qsv (hevc) - HEVC video (Intel Quick Sync Video acceleration)
[vd]     hevc_cuvid (hevc) - Nvidia CUVID HEVC decoder
[vd] Opening decoder hevc
[vd] Looking at hwdec hevc-vulkan...
[vd] Trying hardware decoding via hevc-vulkan.
[vd] Selected decoder: hevc - HEVC (High Efficiency Video Coding)
[vd] Pixel formats supported by decoder: vaapi cuda vulkan yuv444p
[vd] Codec profile: Rext (0x4)
[vd] Requesting pixfmt 'vulkan' from decoder.


(program exits here without playing any video)
```

I referred to @vadash's driver versions that produce a working example, and after doing a full clean reinstall of 537.58 after using DDU to clean my updated driver on my laptop, I can confirm that this is now fully working for me as well. This confirms that NVidia must have introduced a bug in their drivers. Thank you!

**Comment by Erfboom** [comment]
hey guys, i'm eager to test this but it seems the api limit for downloading artifacts in appveyor was exceeded. can anyone share the appimage? or i can be patient and wait?

**Comment by RedTib** [comment]
> 537.58

Using this driver worked for me as well, but it did not work with HDR and 4:4:4 enabled at the same time.

**Comment by ns6089** [comment]
> hey guys, i'm eager to test this but it seems the api limit for downloading artifacts in appveyor was exceeded. can anyone share the appimage? or i can be patient and wait?

https://github.com/ns6089/moonlight-qt/releases/tag/pr1282
Exceeds 25MB attachment limit, hence the roundabout way,

**Comment by Erfboom** [comment]
> > hey guys, i'm eager to test this but it seems the api limit for downloading artifacts in appveyor was exceeded. can anyone share the appimage? or i can be patient and wait?
> 
> https://github.com/ns6089/moonlight-qt/releases/tag/pr1282 Exceeds 25MB attachment limit, hence the roundabout way,

You're too kind, but would you happen to have the AppImage? Am on Linux.

**Comment by ns6089** [comment]
No, sorry.

**Comment by Decbuan** [comment]
Steamdeckoled does not support 444 encoding
image
image

**Comment by Decbuan** [comment]
Steamdeck oled does not support 444 decoding
image

**Comment by Erfboom** [comment]
Needs to be software for AMD I believe.

**Comment by KWottrich** [comment]
> > > hey guys, i'm eager to test this but it seems the api limit for downloading artifacts in appveyor was exceeded. can anyone share the appimage? or i can be patient and wait?
> > 
> > 
> > https://github.com/ns6089/moonlight-qt/releases/tag/pr1282 Exceeds 25MB attachment limit, hence the roundabout way,
> 
> You're too kind, but would you happen to have the AppImage? Am on Linux.

@Erfboom download limit reset: https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/50226576/job/sf7l969npglkxddn/artifacts

**Comment by ns6089** [comment]
I've added it to the same temporary release page https://github.com/ns6089/moonlight-qt/releases/tag/pr1282

**Comment by Erfboom** [comment]
Thanks guys, I was able to pull it from appveyor.

Tests on AMD: works with software only. bitrate requirements go up. windows 11 with a 3080 and sunshine got wonky and i experienced hella latency. rebooting the machine fixed it. (may have helped color banding some :(, but still there). Things do look better though, sharper. can't do 4k@60 without hardware encoding. capped at 1440p@60 for stable frames, but with the bitrate lowered and no ability to change it, i started to see artifcating.

Tests on Intel: lol. I don't know if my iGPU is too old (10th gen comet lake), and I admit i'm running it in a distrobox, but after some fiddling I got hardware decoding to be detected by moonlight. hw decoding works, but not with YUV4, says gpu doesn't support it. vdpauinfo backs that up, don't know how to read vainfo to tell if that's the case. software decoding allows 4:4:4, but i can't get in stream, don't know what I'm missing.

This was all done using the AppImage, opensuse Aeon (tumbleweed distrobox) and opensuse tumbleweed plasma6.

I can whip up a quick vm with an nvidia card to test moonlight there too, but i don't want to be heartbroken when i see that it works great on hw decoding.

**Comment by ns6089** [comment]
@Erfboom
> Tests on AMD

AMD lacks the support for native 4:4:4 on the hardware level. I will add a special "recombined" 4:4:4 mode a bit later, where full 4:4:4 data is spread across a larger 4:2:0 frame.

> Tests on Intel

Intel does support 4:4:4 decoding on gen10 cpus and newer, so it's a driver issue.
Currently moonlight only tries vulkan hardware decoding to not contaminate the testing. This should be Intel ANV driver in your case and it may still have issues with vulkan video extensions.
I guess we can try enabling vaapi too ([it has 4:4:4 support](https://github.com/intel/media-driver/blob/master/README.md#decodingencoding-features)) later if vulkan driver is in a bad state. But the process will be somewhat troublesome (decoder priorities and a myriad of different linux configurations).

**Comment by Erfboom** [comment]
> @Erfboom
> 
> > Tests on AMD
> 
> AMD lacks the support for native 4:4:4 on the hardware level. I will add a special "recombined" 4:4:4 mode a bit later, where full 4:4:4 data is spread across a larger 4:2:0 frame.
> 
> > Tests on Intel
> 
> Intel does support 4:4:4 decoding on gen10 cpus and newer, so it's a driver issue. Currently moonlight only tries vulkan hardware decoding to not contaminate the testing. This should be Intel ANV driver in your case and it may still have issues with vulkan video extensions. I guess we can try enabling vaapi too ([it has 4:4:4 support](https://github.com/intel/media-driver/blob/master/README.md#decodingencoding-features)) later if vulkan driver is in a bad state. But the process will be somewhat troublesome (decoder priorities and a myriad of different linux configurations).

The latency I was talking about is definitely because my CPU can't decode that much data coming through on a higher bitrate, but I do definitely see a difference now between YUV4:4:4 and YUV4:2:0. Wish I could use it!

I suspected it was a driver issue. Intel iGPUs are not in a good place in linux for media. They're fine for the most part but when you get into this stuff you can see the cracks.

I tried VAAPI, so that explains it. I did notice Vulkan errors. Moonlight kept on trying to use GL. I'm not familiar with the Intel ANV driver, but maybe I can give that a shot :). Thanks for your hard work! This is really cool stuff.

**Comment by mirh** [comment]
You need `ANV_VIDEO_DECODE=1`

**Comment by Decbuan** [comment]
> @Erfboom
> 
> > AMD 上的测试
> 
> AMD 在硬件层面上缺乏对 4:4:4 的支持。稍后我将添加一种特殊的“重组”4:4:4 模式，其中完整的 4:4:4 数据分配在更大的 4 :2:0 一帧中。
> 
> > 因果测试
> 
> Intel 确实支持 gen10 cpu 及更新版本上的 4:4:4 解码，因此这是一个驱动程序问题。 目前，moonlight 仅尝试使用 vulkan 硬件解码，足以影响测试。在您的情况下，这应该是 Intel ANV驱动程序，并且它可能仍然存在与 vulkan 视频扩展相关的问题。 我想如果 vulkan 驱动程序处于不良状态，我们稍后也可以尝试启用 vaapi（[它支持 4:4:4](https://github.com/intel/media-driver/blob/master/README.md#decodingencoding-features)）。但这个过程会有些麻烦（解码器优先级和大量不同的linux配置）。

M1 MAX also does not support 4:4:4 decoding.

**Comment by Decbuan** [comment]
> @Erfboom
> 
> > AMD 上的测试
> 
> AMD在硬件层面上缺乏对 4:4:4 的支持。稍后我将添加一种特殊的“重组”4:4:4 模式，其中完整的 4:4:4 数据分配在更大的 4 : 2:0 一帧中。
> 
> > 因果测试
> 
> Intel 确实支持 gen10 cpu 及更新版本上的 4:4:4 解码，因此这是一个驱动程序问题。 目前，moonlight 仅尝试使用 vulkan 硬件解码，足以影响测试。在您的情况下，这应该是 Intel ANV驱动程序，并且它可能仍然存在与 vulkan 视频扩展相关的问题。 我想如果 vulkan 驱动程序处于不良状态，我们稍后也可以尝试启用 vaapi（[它支持 4:4:4](https://github.com/intel/media-driver/blob/master/README.md#decodingencoding-features)）。但这个过程会有些麻烦（解码器优先级和大量不同的linux配置）。
How can we enable 4:4:4 decoding on more devices? Will the Steam Deck OLED have a chance to enable 4:4:4 after it's released? If we can enable the 4:4:4 feature on more mobile devices, it will be more meaningful.

**Comment by Decbuan** [comment]
(deck@steamdeck ~)$ vdpauinfo
display: :0   screen: 0
API version: 1
Information string: G3DVL VDPAU Driver Shared Library version 1.0

Screenshot_20240721_021839

**Comment by Erfboom** [comment]
More tests.

Test on Steamdeck:

Crisp and clear with YUV4:4:4, with software decoding. can handle 1080p@60 just fine though and looks great! 

Wish i could figure out what filter gamescope / steam is using to add noise so i could turn it off. 

More Intel Tests:

Software decoding works with or without ANV_Video_decode. After doing some digging, it looks like that's related to the new IRIS driver? If so, that only supports GEN11 and newer. I have the UHD driver for GEN10. 

A note on the HDR. On KDE6 Plasma, with an HDR monitor, moonlight could not properly match the inbound hdr colorspace to what the intel igpu could decode resulting in a crash. I believe that was related to libplacebo or mesa itself.

This time around, the HDR button was able to be toggled without gamescope, on gnome (no hdr), probably because it's running in a distrobox and tonemapping was applied properly. Not sure what's going on there.

**Comment by mirh** [comment]
Iris is the opengl driver for gen8-9, it has nothing to do with this. 
And vulkan video decode is [possibly](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/21183) going to ship for gen7 too. 

Gen11 gpus are required for 444 [because](https://github.com/intel/media-driver#decodingencoding-features) they are the first to have the required hardware to begin with.

**Comment by cgutman** [comment]
It looks like the FFmpeg bug is being tracked upstream as https://trac.ffmpeg.org/ticket/10847

I'll merge this, but the Nvidia driver crash is probably a ship blocker until we can get a patch to address it (preferably upstreamed).

**Comment by cgutman** [comment]
@ns6089 Thanks for all your hard work on this!

**Comment by PmNz8** [comment]
Hello all, using MoonlightPortable-x64-r2552 I can not use HW for decoding 4:4:4 despite having i5 11400T with HD 730 that should support 4:4:4 decode of H265. I can only get 4:4:4 stream from Sunshine https://github.com/LizardByte/Sunshine/actions/runs/10206571176 when using software decode in Moonlight. 
Moonlight claims there is no HW support: 
image

Maybe some issue with detection of HW decoder capabilities? 
[Moonlight-1722769990.log](https://github.com/user-attachments/files/16487297/Moonlight-1722769990.log)

**Comment by cgutman** [comment]
It's because D3D11VA doesn't have YUV 4:4:4 support yet since Microsoft just updated the DXVA specification to support it and the Intel Windows driver seems to have broken Vulkan Video decoding support. The Intel drivers do support the new DXVA profiles for YUV 4:4:4 but it also requires support in FFmpeg to work.

**Comment by mirh** [comment]
Actually it's the [other way](https://github.com/Nevcairiel/LAVFilters/issues/547) around. 
Since forever the intel drivers already support the old profiles they rolled out on their own, and it's unclear just how much further back in time such support would go (regardless, yes, you need patched ffmpeg)

**Comment by cgutman** [comment]
It's both. Modern Intel drivers expose the old Intel-specific profiles and the new Microsoft-defined official profiles. Unless FFmpeg is willing to accept Intel-specific profiles, I'm going to only support the official profiles which leaves out Ice Lake.

**Comment by mirh** [comment]
I don't see why they wouldn't. It's not like they aren't already supporting proprietary extensions.. and presumably this is just a matter of trying an additional guid, if the official one fail?

**Comment by nyanmisaka** [comment]
The two GUIDs correspond to different dxva structures (the bits are in different order, so it's not just as simple as switching GUIDs). Intel's dxva structure is dumped from the driver DDI and is not in any public documentation. Only Intel knows the details. Unless you want to hardcode it in FFmpeg instead of including the dx header files from Microsoft.

**Comment by KWottrich** [comment]
It looks like the bitrate slider isn't working when YUV 4:4:4 is enabled. It calculates a default value, but changing the slider doesn't persist when you close the settings with the back arrow in the upper left and immediately reopen the menu. Since this is already merged, I created a bug report for this: https://github.com/moonlight-stream/moonlight-qt/issues/1387

**Pull request merged**
